# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f0aed96fdbd9d2d50b2eabaf47c737de"
name = "what-a-day-to-be-alive"
handle = "what-a-day-to-be-alive-1"
application_url = "https://exempt-holdem-bolivia-bow.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://exempt-holdem-bolivia-bow.trycloudflare.com/auth/callback",
  "https://exempt-holdem-bolivia-bow.trycloudflare.com/auth/shopify/callback",
  "https://exempt-holdem-bolivia-bow.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
